create table
  public.match_messages (
    id bigint generated by default as identity,
    match_id uuid not null,
    user_id uuid not null,
    message text not null,
    created_at timestamp with time zone not null default now(),
    constraint match_messages_pkey primary key (id),
    constraint match_messages_match_id_fkey foreign key (match_id) references matches (id),
    constraint match_messages_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

alter publication supabase_realtime add table public.match_messages;