create table
  public.match_searches (
    id bigint generated by default as identity,
    "user_id" uuid not null,
    game_type public.game_type not null,
    match_search_state public.match_search_state not null,
    created_at timestamp with time zone not null default now(),
    constraint match_searches_pkey primary key (id),
    constraint match_searches_user_fkey foreign key ("user_id") references users (id) on update cascade on delete cascade
  ) tablespace pg_default;